SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

# Player movement settings
PLAYER_TURN_SPEED = 180        # Degrees per second
PLAYER_ACCELERATION = 100      # Units per second²
PLAYER_DECELERATION = 50       # Units per second²
PLAYER_MAX_SPEED = 200         # Units per second
PLAYER_MAX_REVERSE_SPEED = 100 # Units per second